In [ ]:
#A.1
import numpy as np
resources_matrix = np.array([
    [10, 20],
    [15, 25],
    [20, 30]
])
allocation_factors = np.array([
    [0.8, 0.2],
    [0.1, 0.9]
])
result = np.dot(resources_matrix, allocation_factors)
print("result matrix")
print(result)


result matrix
[[10.  20. ]
 [14.5 25.5]
 [19.  31. ]]


In [ ]:
#A.2
import numpy as np
shift_a = np.array([
    [50, 60, 55, 70, 65, 80, 75],
    [40, 45, 50, 55, 60, 65, 70],
    [30, 35, 40, 45, 50, 55, 60]
])
shift_b = np.array([
    [45, 55, 50, 65, 60, 75, 70],
    [35, 40, 45, 50, 55, 60, 65],
    [25, 30, 35, 40, 45, 50, 55]
])
total_production = shift_a + shift_b
print("Total Production:")
print(total_production)

Total Production:
[[ 95 115 105 135 125 155 145]
 [ 75  85  95 105 115 125 135]
 [ 55  65  75  85  95 105 115]]


In [ ]:
#A.3
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
forecast_values = np.array([-2, -1, 0, 1, 2])
result = sigmoid(forecast_values)
print("Forecast values:", forecast_values)
print("Sigmoid output:", result)


Forecast values: [-2 -1  0  1  2]
Sigmoid output: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [ ]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_gradient(x):
    s = sigmoid(x)
    return s * (1 - s)
test_values = np.array([-2, -1, 0, 1, 2])
grad_output = sigmoid_gradient(test_values)
print("Input values:", test_values)
print("Sigmoid gradient:", grad_output)


Input values: [-2 -1  0  1  2]
Sigmoid gradient: [0.10499359 0.19661193 0.25       0.19661193 0.10499359]
