In [2]:
import numpy as np

np.random.seed(42)

X = np.array([
    [20, 3, 4],
    [15, 5, 3],
    [30, 2, 2],
    [25, 4, 1],
    [35, 2, 3]
])

y = np.array([[0.0], [0.1667], [0.3333], [0.5833], [1.0000]])

W1 = np.random.randn(3, 3) * 0.1
b1 = np.zeros((1, 3))
W2 = np.random.randn(3, 1) * 0.1
b2 = np.zeros((1, 1))

learning_rate = 0.1
epochs = 5000

print("Initial weights:")
print("W1:", W1)
print("b1:", b1)
print("W2:", W2)
print("b2:", b2)
print()

for epoch in range(epochs):
    z1 = X @ W1 + b1
    a1 = np.maximum(0, z1)
    z2 = a1 @ W2 + b2
    a2 = 1 / (1 + np.exp(-z2))

    loss = np.mean((y - a2) ** 2)

    dL_da2 = -2 * (y - a2) / 5
    da2_dz2 = a2 * (1 - a2)
    dL_dz2 = dL_da2 * da2_dz2

    dL_dW2 = a1.T @ dL_dz2
    dL_db2 = np.sum(dL_dz2, axis=0, keepdims=True)

    dz2_da1 = W2.T
    dL_da1 = dL_dz2 @ dz2_da1
    da1_dz1 = (z1 > 0).astype(float)
    dL_dz1 = dL_da1 * da1_dz1

    dL_dW1 = X.T @ dL_dz1
    dL_db1 = np.sum(dL_dz1, axis=0, keepdims=True)

    W1 -= learning_rate * dL_dW1
    b1 -= learning_rate * dL_db1
    W2 -= learning_rate * dL_dW2
    b2 -= learning_rate * dL_db2

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.6f}")

print(f"\nFinal loss: {loss:.6f}")

print("\nTrained parameters:")
print("W1:")
print(W1)
print("\nb1:")
print(b1)
print("\nW2:")
print(W2)
print("\nb2:")
print(b2)

predictions = a2 * 12 + 18
actual = np.array([18, 20, 22, 25, 30])

print("\nPredictions:")
for i in range(5):
    print(f"Point {i+1}: Prediction = {predictions[i][0]:.2f}, Actual = {actual[i]}, Difference = {predictions[i][0]-actual[i]:.2f}")

Initial weights:
W1: [[ 0.04967142 -0.01382643  0.06476885]
 [ 0.15230299 -0.02341534 -0.0234137 ]
 [ 0.15792128  0.07674347 -0.04694744]]
b1: [[0. 0. 0.]]
W2: [[ 0.054256  ]
 [-0.04634177]
 [-0.04657298]]
b2: [[0.]]

Epoch 0, Loss: 0.133229
Epoch 1000, Loss: 0.041494
Epoch 2000, Loss: 0.036358
Epoch 3000, Loss: 0.045996
Epoch 4000, Loss: 0.041843

Final loss: 0.042171

Trained parameters:
W1:
[[-0.26269514 -0.01382643  0.30559859]
 [-0.16634782 -0.02341534 -0.27263029]
 [ 1.36778412  0.07674347 -0.9388923 ]]

b1:
[[ 0.09789509  0.         -0.99449034]]

W2:
[[-1.09890382]
 [-0.04634177]
 [ 0.55545821]]

b2:
[[-2.32540573]]

Predictions:
Point 1: Prediction = 19.12, Actual = 18, Difference = 1.12
Point 2: Prediction = 19.07, Actual = 20, Difference = -0.93
Point 3: Prediction = 25.39, Actual = 22, Difference = 3.39
Point 4: Prediction = 23.73, Actual = 25, Difference = -1.27
Point 5: Prediction = 26.12, Actual = 30, Difference = -3.88
